### ISSUE TITLE
form submissions with Email addresses that do not contain periods return error

### ISSUE THREAD

**Issue by skorasaurus** [opencleveland/refundcleveland#42]
When submitting the form and the email value not contain a period in it (e.g. "sfdfsd@ss2com"); 

error is returned
```
ValueError at /store-data/

The view peoples_budget.views.store_data didn't return an HttpResponse object. It returned None instead.
```

full error messages at https://gist.github.com/skorasaurus/6c8a7014164f43d440b4afb224a03cc8

Perhaps will need to write a validator? (https://docs.djangoproject.com/en/3.1/ref/validators/#django.core.validators.EmailValidator)

**Comment by jessicalynch** [comment]
I think this might be related to what we were talking about earlier -- there is an if statement on line 59 of views.py, "if form.is_valid():", but there is no branch written for if the form is not valid.

**Comment by skorasaurus** [comment]
thank you!
