### ISSUE TITLE
Street address validation

### ISSUE THREAD

**Issue by jessicalynch** [opencleveland/refundcleveland#51]
We currently don't have any validation for the street address input in the submit form -- the USPS API might be a good option: https://www.usps.com/business/web-tools-apis/address-information-api.htm

**Comment by skorasaurus** [comment]
another one that I mentioned as well is geocode.earth; 

A tentative idea that I'm throwing out:  user begins to input the  address > (with a geocoding service), spits out the lat lon (behind the scenes, user just sees their address in an autocomplete dropdown that would be filled in)  > use [which-polygon](https://github.com/mapbox/which-polygon) to find out what ward that the point belong to, and assign that ward value to it.

**Comment by adamfishman** [comment]
for geocoding we can use the US Census bureau or Google.
US Census bureau: 
    https://geocoding.geo.census.gov/
    python lib: https://pypi.org/project/censusgeocode/

Google:
    https://pypi.org/project/censusgeocode/

From these APIs, we get Lat/Lon, and then can look up ward using Will's previous work here:
    https://github.com/skorasaurus/cleboundaries

also, our postgres database can use postGIS, so we can use that or a library in JS to look up via geoJSON

**Comment by adamfishman** [comment]
decided on one stop shopping using google civic api!

https://developers.google.com/civic-information/docs/v2/representatives

**Comment by skorasaurus** [comment]
For posterity: 

I couldn't figure out how to find do the auto complete for the address (to do the geocoding) in a non-leaflet input; as well how to do the which ward is this in; and Adam found the google civic api; so we've gone with that for now.
