### ISSUE TITLE
ward field is not populated when find ward button is run 

### ISSUE THREAD

**Issue by skorasaurus** [opencleveland/refundcleveland#68]
On the website, 
I noticed that when an address is input into the field 
and find ward button is pressed, the ward number wasn't not being populated/filled into the id_ward input field. 

when the find ward button is pressed, lookup_address does make a fetch query - 
![lookup_address](https://user-images.githubusercontent.com/955351/107661343-34e04680-6c57-11eb-9d4a-1795b007636a.png)

and this is the response: 
`HTTP/1.1 200 OK
Connection: keep-alive
Server: gunicorn/20.0.4
Date: Thu, 11 Feb 2021 15:48:17 GMT
Content-Type: text/html; charset=utf-8
X-Frame-Options: DENY
Content-Length: 19
X-Content-Type-Options: nosniff
Referrer-Policy: same-origin
Via: 1.1 vegur`

**Comment by adamfishman** [comment]
I just tested it with my address and it worked...
but it looks like if I type an address which doesn't properly geocode, we're not dealing with the 500 error
seems to be a different issue than what you're seeing.  What address did you use?

**Comment by skorasaurus** [comment]
I've tried a couple different addresses with different results: 

no response in console and ward field not populated: 
1921 MAYVIEW AVE (also tried 1921 MAYVIEW) 
3808 LEOPOLD AVE (also tried 3808 LEOPOLD) 
18327 HOMEWAY

500 error in console: 
12008 WAYLAND AVE
5103 detroit

worked as expected: 
2100 Lakeside

If you need random addresses to try out, check out twitter.com/everylot_cle :)
