### ISSUE TITLE
Share Your Budget Submission not working on /store-data/

### ISSUE THREAD

**Issue by shuxrei** [opencleveland/refundcleveland#73]
After submitting email and ward #, the links to share the budget on Facebook is not working and no link is present for Twitter.  These links should match the behavior on the share links from the /view/ page

**Comment by skorasaurus** [comment]
I swear I fixed this yesterday, silly me, I'll work on this.

**Comment by skorasaurus** [comment]
I removed it for now; I haven't figured out how to get an accurate link to display on this page (But I got to work on the view budget page)

**Comment by shuxrei** [comment]
I added some logic within the views.py file to create an object representing the URL for django-social-share to use.  It worked locally so fingers crossed!
