### ISSUE TITLE
Share to Facebook results in Not Found link

### ISSUE THREAD

**Issue by shuxrei** [opencleveland/refundcleveland#74]
When sharing to Facebook from the /view/ page, the link populates a "Not Found" preview.  If the link is clicked after sharing, the user is directed to a Not Found page.

Example: https://www.refundcleveland.com/7a573a22-f172-421b-9b1e-daaa98caef1e/view/%7B%7B%20id%20%7D%7D/view/?fbclid=IwAR0xG78-PKynX12Q4q07N3vCk8neAcjIKB_Wnd8Z1_3rBwn33t8VpM07ffU

**Comment by shuxrei** [comment]
This is the same link that populates for Twitter and also results in Not Found.

**Comment by jessicalynch** [comment]
Perhaps we should remove the links until it's resolved. I can add a meta image so there is a preview (when pasting the link manually on fb/twitter)

**Comment by skorasaurus** [comment]
I fixed this in the poorly named fix-73 branch.
